# NumPy Homework

# A

## 1) import numpy library with his usual alias!

In [1]:
# < write your code here >
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

## 2) Create a random matrix, which has 2 columns and 20 rows. With this we will then create a pandas DataFrame!

In [2]:
ratings_values = np.random.randint(low=1, high=6, size=(20, 2))
ratings = pd.DataFrame(ratings_values, columns=['Price', 'Quality'])
print(ratings_values)
print()
display(ratings)

[[2 2]
 [1 1]
 [3 3]
 [3 1]
 [3 5]
 [1 5]
 [3 5]
 [4 4]
 [4 5]
 [2 1]
 [1 4]
 [3 2]
 [4 2]
 [4 2]
 [2 1]
 [2 5]
 [2 1]
 [2 4]
 [4 1]
 [2 1]]



Price  Quality
0       2        2
1       1        1
2       3        3
3       3        1
4       3        5
5       1        5
6       3        5
7       4        4
8       4        5
9       2        1
10      1        4
11      3        2
12      4        2
13      4        2
14      2        1
15      2        5
16      2        1
17      2        4
18      4        1
19      2        1

## 3) Create two vectors from the previous DataFrame. We will use the same values from the previous DataFrame which we already have been created. The first one contains the evaluations which show the customer satisfaction for the prices, and the second one contains for the quality. How big how good! We will then print the vectors.

##### Hint: pd.DataFrame['column_name'] gives us a Series from a DataFrame. We can use it with the same functions as DataFrames.

In [3]:
price =  ratings['Price'].values
quality =ratings['Quality'].values


print('Price: ', price)
print('Quality: ', quality)

Price:  [2 1 3 3 3 1 3 4 4 2 1 3 4 4 2 2 2 2 4 2]
Quality:  [2 1 3 1 5 5 5 4 5 1 4 2 2 2 1 5 1 4 1 1]


## 4) Find the total numbers of visitors. (BU KONU ILE ILGILI BIR DATA YOK)

In [ ]:
visitors_count = # < write your code here >
##  DATA YOK. 
print('Number of visitors:', visitors_count)

## 5) Find and print the average ratings for each column using numpy functions (we will find the mean and median values)

In [9]:
print('The mean of the price ratings: ', <.........................>) # < write your code here >
print('The median of the price ratings', <.........................>) # < write your code here >

print('The mean of the quality ratings: ', <.......................>) # < write your code here >
print('The median of the quality ratings', <.......................>) # < write your code here >

In [8]:
price_mean = np.mean(ratings['Price'])
price_median = np.median(ratings['Price'])

# Print the mean and median ratings for the Price column
print('The mean of the price ratings: ', price_mean)
print('The median of the price ratings: ', price_median)

# Calculate the mean and median ratings for the Quality column using numpy functions
quality_mean = np.mean(ratings['Quality'])
quality_median = np.median(ratings['Quality'])

# Print the mean and median ratings for the Quality column
print('The mean of the quality ratings: ', quality_mean)
print('The median of the quality ratings: ', quality_median)

The mean of the price ratings:  2.6
The median of the price ratings:  2.5
The mean of the quality ratings:  2.75
The median of the quality ratings:  2.0


## 6) Create a new vector which is the average of the ratings of two columns, price and quality. We will name it as mean_ratings. It will show the average rating for each customer. Round elements of the array to the nearest integer.

In [13]:
mean_ratings = np.mean(ratings[['Price', 'Quality']], axis=1).round()
print(mean_ratings)

0     2.0
1     1.0
2     3.0
3     2.0
4     4.0
5     3.0
6     4.0
7     4.0
8     4.0
9     2.0
10    2.0
11    2.0
12    3.0
13    3.0
14    2.0
15    4.0
16    2.0
17    3.0
18    2.0
19    2.0
dtype: float64


## 7) Create ratings_values matrix again with the all three vectors. Average ratings, which has just been calculated in the previous exercise, should be the third column of the new matrix. All values in the matrix should be integer! New matrix should have 20 rows and 3 columns!

In [16]:
new_ratings_values = np.column_stack((ratings['Price'], ratings['Quality'], mean_ratings))
print(new_ratings_values)
print(type(new_ratings_values))
print(new_ratings_values.shape)

[[2. 2. 2.]
 [1. 1. 1.]
 [3. 3. 3.]
 [3. 1. 2.]
 [3. 5. 4.]
 [1. 5. 3.]
 [3. 5. 4.]
 [4. 4. 4.]
 [4. 5. 4.]
 [2. 1. 2.]
 [1. 4. 2.]
 [3. 2. 2.]
 [4. 2. 3.]
 [4. 2. 3.]
 [2. 1. 2.]
 [2. 5. 4.]
 [2. 1. 2.]
 [2. 4. 3.]
 [4. 1. 2.]
 [2. 1. 2.]]
<class 'numpy.ndarray'>
(20, 3)


In [17]:
mean_ratings = np.round(mean_ratings).astype(int)
mean_ratings = np.array(mean_ratings, dtype=[('Average', int)])

In [18]:
new_ratings = pd.DataFrame(new_ratings_values, columns=['Price', 'Quality', 'Average'])
display(new_ratings)

Price  Quality  Average
0     2.0      2.0      2.0
1     1.0      1.0      1.0
2     3.0      3.0      3.0
3     3.0      1.0      2.0
4     3.0      5.0      4.0
5     1.0      5.0      3.0
6     3.0      5.0      4.0
7     4.0      4.0      4.0
8     4.0      5.0      4.0
9     2.0      1.0      2.0
10    1.0      4.0      2.0
11    3.0      2.0      2.0
12    4.0      2.0      3.0
13    4.0      2.0      3.0
14    2.0      1.0      2.0
15    2.0      5.0      4.0
16    2.0      1.0      2.0
17    2.0      4.0      3.0
18    4.0      1.0      2.0
19    2.0      1.0      2.0

# B

## 1) Create *Mean Absolute Error (MAE)* function

\begin{equation}
MAE=\frac{1}{n}\sum_{i=1}^n|target_i - predictions_i|
\end{equation}

In [19]:
def mae(target, predictions):
    return  mae

In [20]:
def mae(target, predictions):
    mae = np.mean(np.abs(predictions - target))
    return mae

## 2) Create two arrays each of them has $100$ observations. We will use them for *target* and *predictions* labelling. The target array should consist only $0$ or $1$ values which are random created, while predictions only integer $1$. The target array should have a *binomial distribution* which gives $1$ with $60$% probability.

In [21]:
target = np.random.binomial(1, 0.6, size=100)
predictions = np.ones(100, dtype=int)

print(target)
print()
print(predictions)

[1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 0 0 1 1 1 1 1 1 1 1 1 1 0 0 1 1 0 1 1 0 1 1
 1 1 1 0 0 1 0 1 1 1 1 1 1 1 1 1 1 1 1 1 0 0 1 1 1 1 1 1 1 1 0 1 1 1 0 0 1
 1 1 1 1 1 0 1 0 0 0 1 0 1 0 1 1 0 0 1 0 0 1 0 1 0 0]

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


## 3) Find the *MAE* with your mae function

In [22]:
mean_absolute_error =  mae(target, predictions)
print(mean_absolute_error)

0.33


## 4)  Run the code in this step. Observe the printed outputs. Try to run the codes a few times from step 2. What do you think about the results? Give your thoughts shortly with 3 - 5 sentences about why two outputs are the same. What is your conclusion?

In [23]:
print(1-np.mean(target))

print(mean_absolute_error)

0.32999999999999996
0.33


 ### <İlk kod satırı, dizideki 1'lerin oranını sayarak hedef ('target') dizinin ortalamasını hesaplar. İkinci kod satırı, hedef ve tahmin('prediction') dizileri arasındaki ortalama mutlak hatayı hesaplar.

İlk kod satırının çıktısı sabittir, çünkü yalnızca bu durumda her zaman 0,6 olan hedef dizide 1 alma olasılığına bağlıdır.

İkinci kod satırının çıktısı, hedef ve tahmin dizilerinin rasgele oluşturulmuş değerlerine bağlı olduğu için değişir ve hedef dizide 1 alma olasılığından etkilenmez.

Dolayısıyla bu iki kod satırının çıktıları BIRBIRI ILE ILISKILI DEGILDIR.>

## 5) We have always chosen $1$ in our predictions, but the actual values at the target have changed each time. How likely is it that we got it right each time, and what determines this?

 ### < Tüm tahminlerimizde 1'i seçtiğimiz için, her seferinde doğru çıkma olasılığı, hedef dizideki 1'lerin oranına eşittir. Bu durumda, hedef dizinin 1 olma olasılığı %60 olan bir binom dağılımı vardır. Bu nedenle ortalama olarak değerlerin %60'ını doğru tahmin etmeyi bekleriz. Ancak, 100 gözlemlik küçük bir örneklem kullandığımız için, kodu her çalıştırdığımızda sonuçlar değişebilir. Özetle, doğru olma olasılığı hedef dizideki 1'lerin oranına bağlıdır ve örneğin rastgeleliği sonuçların değişmesine neden olabilir. >

# C

## 1) Create a Pythagorean function using *np.dot()* to calculate vector length

$$v = [x, y] ==> len_v = \sqrt{x^2+y^2}$$

In [24]:
def pythagorean_length(vector):
    return np.sqrt(np.dot(vector, vector))

## 2) Calculate the length of the given vector using your *pythagorean_length* function and check your result comparing with the given

In [25]:
a = np.array([3, 4])

print(pythagorean_length(a))
print(((a[0] ** 2) + (a[1] ** 2)) ** 0.5)

5.0
5.0


## 3) Find the shortest distance (Euclidean distance) using *np.dot()* between the given two vectors and compare the results to check

In [26]:
a = np.array([5, 6])
b = np.array([1, 3])

c = np.dot(a-b, a-b) ** 0.5
print('The distance between a and b is', c)

from scipy.spatial import distance
print('The distance between a and b should be', distance.euclidean(a, b))

The distance between a and b is 5.0
The distance between a and b should be 5.0


# D - Obfuscating Data

It is best to obfuscate data by multiplying the numerical features (they can be seen as the matrix $X$) by an invertible matrix $P$. 

$$
X' = X \times P
$$

Try to do that and check how the features' values will look like after the transformation. By the way, the invertible property is important here so make sure that $P$ is indeed invertible.

In [27]:
# pd.DataFrame
columns = ['gender', 'age', 'salary', 'family_members']
data = np.array([np.random.choice([0, 1], size=1000), 
                 np.random.randint(18, 100, 1000), 
                 np.random.normal(25000, 5000, 1000).astype(int), 
                 np.random.randint(0, 10, 1000)
                ])

personal_data = pd.DataFrame(data.T, columns=columns)
display(personal_data.tail(10))

gender  age  salary  family_members
990       0   70   17932               6
991       1   30   25399               7
992       1   27   25257               6
993       0   85   26521               0
994       1   79   17607               4
995       0   35   20785               3
996       0   36   20593               0
997       0   79   20915               2
998       0   23   27165               0
999       1   94   29634               1

In [29]:
# Generate a random invertible matrix P
P = np.random.rand(4, 4)
while np.linalg.det(P) == 0:
    P = np.random.rand(4, 4)

In [30]:
X = personal_data[['gender', 'age', 'salary', 'family_members']].to_numpy()
X_obfuscated = np.dot(X, P)

In [31]:
print('Original feature matrix X:')
print(X[:10, :])
print('\nObfuscated feature matrix X_obfuscated:')
print(X_obfuscated[:10, :])

Original feature matrix X:
[[    1    78 24674     1]
 [    1    64 23066     7]
 [    1    91 23656     5]
 [    1    92 23977     7]
 [    1    41 20140     1]
 [    1    26 21351     8]
 [    1    84 23889     6]
 [    0    71 24203     0]
 [    0    85 18468     0]
 [    1    55 30100     6]]

Obfuscated feature matrix X_obfuscated:
[[20218.44804258  6007.66355551  1763.66671178  7296.36541486]
 [18901.42839151  5612.68460704  1650.0373507   6815.61837133]
 [19390.21341782  5778.23330166  1697.39213104  7008.47448188]
 [19654.15613713  5857.94468513  1721.48203481  7103.84218505]
 [16497.70863921  4882.82372871  1434.05017211  5938.74175981]
 [17488.51750229  5165.53651582  1519.8527655   6284.3024177 ]
 [19579.66082225  5828.50149648  1712.65548321  7071.79164868]
 [19830.14681514  5886.10374109  1727.44352186  7152.15892044]
 [15139.00591342  4520.21929096  1325.93646224  5480.56911217]
 [24656.70835359  7294.80037138  2143.97757326  8871.73188799]]


**(Hint:** https://numpy.org/doc/stable/reference/random/generator.html **)**

In [ ]:
# < write your code here >

In [ ]:
# < write your code here >

#### Can you guess the customers' ages or income after the transformation?

In [ ]:
# Secure Data
pd.DataFrame(<............>).describe() # < write your code here >

#### Tersine çevrilebilir bir matris ile sayısal özelliklerin çarpılması yoluyla veriler bulanıklaştırıldığı için, yalnızca dönüştürülen verilere dayanarak müşterilerin yaşları veya gelirleri hakkında doğru tahminler yapmak zor olacaktır. define() yönteminin çıktısı, dönüştürülen verilerin her özellik için ortalama, standart sapma, minimum ve maksimum değerler gibi temel istatistiksel özelliklerini gösterir, ancak bu bilgiler orijinal müşteri yaşları veya gelir değerleriaçısından doğrudan yorumlanamaz.  Bu nedenle, dönüştürülen veriler, yetkisiz erişime veya kötü niyetli kullanıma karşı güvenli kabul edilebilir.
...

#### Can you recover the original data from $X'$ if you know $P$? Try to check that with calculations by moving $P$ from the right side of the formula above to the left one. The rules of matrix multiplication are really helpful here.

In [ ]:
# < write your code here >

In [ ]:
# Printing all three cases for a few customers

In [ ]:
# Original Data
personal_data.tail(10)

In [ ]:
# Secure Data
pd.DataFrame(<............>).tail(10)  # < write your code here >

In [ ]:
# Recovered Data
pd.set_option('display.float_format', '{:.2f}'.format)
pd.DataFrame(<............>).astype('int').tail(10) # < write your code here >

#### write your conlusion here
...

---

# USEFUL INFORMATIONS

##### Matrices and Matrix Operations

- **A matrix** is a rectangular numeric table or two-dimensional array consisting of m rows and n columns.
- **A transpose of the matrix** is a matrix operation when its rows become columns with the same numbers.- **Dummy code** is a simple code that doesn't mean anything.
- **An identity matrix** is a square matrix with ones on the main diagonal and zeros elsewhere.
- **An inverse matrix** for a square matrix A is a matrix A with a superscript -1 whose product with A is equal to the identity matrix.
- **Invertible matrices** are matrices that have an inverse.
- **Non-invertible** are matrices that don't have an inverse.

# Properties of Matrices

Matrices have many properties in Linear Algebra. A few of them are listed here which can help with the analytical proof in this project.

<table>
<tr>
<td>Distributivity</td><td>$A(B+C)=AB+AC$</td>
</tr>
<tr>
<td>Non-commutativity</td><td>$AB \neq BA$</td>
</tr>
<tr>
<td>Associative property of multiplication</td><td>$(AB)C = A(BC)$</td>
</tr>
<tr>
<td>Multiplicative identity property</td><td>$IA = AI = A$</td>
</tr>
<tr>
<td></td><td>$A^{-1}A = AA^{-1} = I$
</td>
</tr>    
<tr>
<td></td><td>$(AB)^{-1} = B^{-1}A^{-1}$</td>
</tr>    
<tr>
<td>Reversivity of the transpose of a product of matrices,</td><td>$(AB)^T = B^TA^T$</td>
</tr>    
</table>

---