# NumPy Homework

# A

## 1) import numpy library with his usual alias!

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

## 2) Create a random matrix, which has 2 columns and 20 rows. With this we will then create a pandas DataFrame!

In [3]:
ratings_values = np.random.randint(10, size=(20,2))   
ratings = pd.DataFrame(ratings_values, columns=['Price', 'Quality'])
print(ratings_values)
print()
display(ratings)

[[3 1]
 [4 4]
 [7 1]
 [3 5]
 [0 5]
 [6 6]
 [5 9]
 [4 2]
 [1 5]
 [4 5]
 [8 4]
 [9 3]
 [1 0]
 [1 2]
 [4 0]
 [2 5]
 [9 1]
 [2 4]
 [0 6]
 [8 1]]



Price  Quality
0       3        1
1       4        4
2       7        1
3       3        5
4       0        5
5       6        6
6       5        9
7       4        2
8       1        5
9       4        5
10      8        4
11      9        3
12      1        0
13      1        2
14      4        0
15      2        5
16      9        1
17      2        4
18      0        6
19      8        1

## 3) Create two vectors from the previous DataFrame. We will use the same values from the previous DataFrame which we already have been created. The first one contains the evaluations which show the customer satisfaction for the prices, and the second one contains for the quality. How big how good! We will then print the vectors.

##### Hint: pd.DataFrame['column_name'] gives us a Series from a DataFrame. We can use it with the same functions as DataFrames.

In [5]:
price =   ratings['Price'].values 
quality = ratings['Quality'].values


print('Price: ', price)
print('Quality: ', quality)

Price:  [3 4 7 3 0 6 5 4 1 4 8 9 1 1 4 2 9 2 0 8]
Quality:  [1 4 1 5 5 6 9 2 5 5 4 3 0 2 0 5 1 4 6 1]


## 4) Find the total numbers of visitors.

In [6]:
visitors_count = len(ratings) 

print('Number of visitors:', visitors_count)

Number of visitors: 20


## 5) Find and print the average ratings for each column using numpy functions (we will find the mean and median values)

In [7]:
print('The mean of the price ratings: ', ratings['Price'].mean()) # < write your code here >
print('The median of the price ratings', np.median(ratings['Price'],axis = 0)) # < write your code here >

print('The mean of the quality ratings: ', ratings['Quality'].mean()) # < write your code here >
print('The median of the quality ratings', np.median(ratings['Quality'],axis = 0)) # < write your code here >

The mean of the price ratings:  4.05
The median of the price ratings 4.0
The mean of the quality ratings:  3.45
The median of the quality ratings 4.0


## 6) Create a new vector which is the average of the ratings of two columns, price and quality. We will name it as mean_ratings. It will show the average rating for each customer. Round elements of the array to the nearest integer.

In [8]:
mean_ratings = np.rint((ratings['Price'] + ratings['Quality'] )*0.5).astype(int)
print(mean_ratings)

0     2
1     4
2     4
3     4
4     2
5     6
6     7
7     3
8     3
9     4
10    6
11    6
12    0
13    2
14    2
15    4
16    5
17    3
18    3
19    4
dtype: int32


## 7) Create ratings_values matrix again with the all three vectors. Average ratings, which has just been calculated in the previous exercise, should be the third column of the new matrix. All values in the matrix should be integer! New matrix should have 20 rows and 3 columns!

In [22]:
new_ratings_values = np.array([ratings_values[:,0],ratings_values[:,1],mean_ratings]).T
print(new_ratings_values)
print(type(new_ratings_values))
print(new_ratings_values.shape)


[[3 1 2]
 [4 4 4]
 [7 1 4]
 [3 5 4]
 [0 5 2]
 [6 6 6]
 [5 9 7]
 [4 2 3]
 [1 5 3]
 [4 5 4]
 [8 4 6]
 [9 3 6]
 [1 0 0]
 [1 2 2]
 [4 0 2]
 [2 5 4]
 [9 1 5]
 [2 4 3]
 [0 6 3]
 [8 1 4]]
<class 'numpy.ndarray'>
(20, 3)


In [23]:
new_ratings = pd.DataFrame(new_ratings_values, columns=['Price', 'Quality', 'Average'])
display(new_ratings)

Price  Quality  Average
0       3        1        2
1       4        4        4
2       7        1        4
3       3        5        4
4       0        5        2
5       6        6        6
6       5        9        7
7       4        2        3
8       1        5        3
9       4        5        4
10      8        4        6
11      9        3        6
12      1        0        0
13      1        2        2
14      4        0        2
15      2        5        4
16      9        1        5
17      2        4        3
18      0        6        3
19      8        1        4

# B

## 1) Create *Mean Absolute Error (MAE)* function

\begin{equation}
MAE=\frac{1}{n}\sum_{i=1}^n|target_i - predictions_i|
\end{equation}

In [24]:
def mae(target, predictions):
    return  np.abs(target - predictions).mean()

## 2) Create two arrays each of them has $100$ observations. We will use them for *target* and *predictions* labelling. The target array should consist only $0$ or $1$ values which are random created, while predictions only integer $1$. The target array should have a *binomial distribution* which gives $1$ with $60$% probability.

In [25]:
target = np.random.binomial(1,0.6,100) # n=1 p = 0.6 size = 100
predictions = np.ones(100, dtype = int)

print(target)
print()
print(predictions)

[0 0 0 1 1 1 1 1 0 0 1 1 0 1 0 1 1 0 1 1 0 1 1 0 0 0 1 0 1 1 1 0 1 1 0 1 1
 1 1 1 1 1 0 0 1 0 0 0 1 0 0 1 1 0 1 0 1 0 0 0 1 0 1 0 1 0 1 0 0 0 0 1 0 1
 1 0 0 1 0 1 1 1 1 1 1 1 1 0 1 0 1 1 1 1 1 1 1 0 0 1]

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


## 3) Find the *MAE* with your mae function

In [26]:
mean_absolute_error = mae(target, predictions)

## 4)  Run the code in this step. Observe the printed outputs. Try to run the codes a few times from step 2. What do you think about the results? Give your thoughts shortly with 3 - 5 sentences about why two outputs are the same. What is your conclusion?

In [27]:
print(1-np.mean(target))

print(mean_absolute_error)

0.42000000000000004
0.42


The mean absolute error measures the average differences between predicted values and actual values.When we examine the results, we can see that they provide a reasonable estimate of model accuracy.

## 5) We have always chosen $1$ in our predictions, but the actual values at the target have changed each time. How likely is it that we got it right each time, and what determines this?

If the actual target values have changed each time, it is possible that your model is not generalizing well to new data, and you may need to re-evaluate your approach. This could involve collecting more data, improving the quality of the data, selecting a different algorithm, or tweaking the parameters of the model.

# C

## 1) Create a Pythagorean function using *np.dot()* to calculate vector length

$$v = [x, y] ==> len_v = \sqrt{x^2+y^2}$$

In [28]:
def pythagorean_length(vector):
    return np.sqrt(np.dot(vector, vector))

## 2) Calculate the length of the given vector using your *pythagorean_length* function and check your result comparing with the given

In [30]:
a = np.array([3, 4])

print(pythagorean_length(a))

print(((a[0] ** 2) + (a[1] ** 2)) ** 0.5)

5.0
5.0


## 3) Find the shortest distance (Euclidean distance) using *np.dot()* between the given two vectors and compare the results to check

In [38]:
a = np.array([5, 6])
b = np.array([1, 3])
d = a - b
c =  distance = np.sqrt(np.dot(d, d))
print('The distance between a and b is', c)

from scipy.spatial import distance
print('The distance between a and b should be', distance.euclidean(a, b))

The distance between a and b is 5.0
The distance between a and b should be 5.0


# D - Obfuscating Data

It is best to obfuscate data by multiplying the numerical features (they can be seen as the matrix $X$) by an invertible matrix $P$. 

$$
X' = X \times P
$$

Try to do that and check how the features' values will look like after the transformation. By the way, the invertible property is important here so make sure that $P$ is indeed invertible.

## 1) Protect customers' personal data. It is necessary to develop a data transformation algorithm that makes it difficult to recover personal information in case the data falls into the wrong hands. This is called data masking or data obfuscation. However, the data must be protected in such a way that the quality of the machine learning models does not suffer. You don't need to choose the best model, just prove that the algorithm works correctly.

In [43]:
# pd.DataFrame
columns = ['gender', 'age', 'salary', 'family_members']
data = np.array([np.random.choice([0, 1], size=1000), 
                 np.random.randint(18, 100, 1000), 
                 np.random.normal(25000, 5000, 1000).astype(int), 
                 np.random.randint(0, 10, 1000)
                ])

personal_data = pd.DataFrame(data.T, columns=columns)
display(personal_data.tail(10))

gender  age  salary  family_members
990       0   85   19621               7
991       1   56   29568               1
992       1   22   17894               9
993       0   62   27874               4
994       0   42   21338               9
995       1   19   30309               8
996       1   39   29381               4
997       0   97   28046               6
998       1   84   25447               0
999       0   23   25702               5

In [44]:
X = personal_data.values


array([[    1,    84, 17139,     9],
       [    1,    65, 26953,     7],
       [    0,    61, 35364,     9],
       ...,
       [    0,    97, 28046,     6],
       [    1,    84, 25447,     0],
       [    0,    23, 25702,     5]])

In [55]:
P = np.random.randint(0,10, (1000,1000))
P

array([[2, 0, 2, ..., 1, 5, 5],
       [7, 6, 0, ..., 3, 3, 5],
       [6, 0, 5, ..., 2, 5, 4],
       ...,
       [4, 5, 1, ..., 3, 6, 4],
       [0, 6, 2, ..., 1, 3, 6],
       [3, 3, 4, ..., 1, 1, 6]])

**(Hint:** https://numpy.org/doc/stable/reference/random/generator.html **)**

In [58]:
X_obf = np.dot(P,X)
X_obf 

array([[     2193,    266169, 110973024,     19780],
       [     2082,    253910, 107393074,     19349],
       [     2252,    270286, 114205683,     20632],
       ...,
       [     2162,    263313, 113843841,     20424],
       [     2226,    266405, 114553204,     20754],
       [     2150,    261827, 110667180,     20135]])

In [ ]:
# X = np.dot(np.linalg.inv(P),X_obf)


## 2) Can you guess the customers' ages or income after the transformation?

In [68]:
# Secure Data
pd.DataFrame(X_obf).describe() # < write your code here >

0              1             2             3
count  1000.00000    1000.000000  1.000000e+03   1000.000000
mean   2209.55200  264233.496000  1.126245e+08  20295.465000
std      63.25229    5880.722572  2.349264e+06    484.610518
min    2019.00000  248558.000000  1.061787e+08  18783.000000
25%    2167.00000  260252.250000  1.110016e+08  19942.000000
50%    2211.50000  264302.500000  1.126783e+08  20309.500000
75%    2252.00000  268234.250000  1.141448e+08  20626.000000
max    2448.00000  283045.000000  1.187060e+08  21807.000000

I think it is not possible to predict the age or income of customers after conversion.

## 3) Can you recover the original data from $X'$ if you know $P$? Try to check that with calculations by moving $P$ from the right side of the formula above to the left one. The rules of matrix multiplication are helpful here.

In [78]:
X_orj=np.dot(np.linalg.inv(P),X_obf)

In [ ]:
# Printing all three cases for a few customers

In [73]:
# Original Data
personal_data.tail(10)

gender  age  salary  family_members
990       0   85   19621               7
991       1   56   29568               1
992       1   22   17894               9
993       0   62   27874               4
994       0   42   21338               9
995       1   19   30309               8
996       1   39   29381               4
997       0   97   28046               6
998       1   84   25447               0
999       0   23   25702               5

In [74]:
# Secure Data
pd.DataFrame(X_obf).tail(10)  # < write your code here >

0       1          2      3
990  2242  260882  110214989  19875
991  2176  253818  108720800  19634
992  2198  258846  112459145  19876
993  2271  275482  115348417  20786
994  2231  275430  116137485  21044
995  2281  273579  115395314  21045
996  2190  254208  110230455  19939
997  2162  263313  113843841  20424
998  2226  266405  114553204  20754
999  2150  261827  110667180  20135

In [79]:
# Recovered Data
pd.set_option('display.float_format', '{:.2f}'.format)
pd.DataFrame(X_orj).astype('int').tail(10) # < write your code here >

0   1      2  3
990  0  85  19621  7
991  0  55  29567  0
992  0  21  17893  8
993  0  61  27873  3
994  0  41  21337  8
995  1  19  30309  8
996  1  39  29381  4
997  0  97  28046  6
998  0  83  25446  0
999  0  23  25702  5

#### write your conlusion here
...

---

# USEFUL INFORMATIONS

##### Matrices and Matrix Operations

- **A matrix** is a rectangular numeric table or two-dimensional array consisting of m rows and n columns.
- **A transpose of the matrix** is a matrix operation when its rows become columns with the same numbers.- **Dummy code** is a simple code that doesn't mean anything.
- **An identity matrix** is a square matrix with ones on the main diagonal and zeros elsewhere.
- **An inverse matrix** for a square matrix A is a matrix A with a superscript -1 whose product with A is equal to the identity matrix.
- **Invertible matrices** are matrices that have an inverse.
- **Non-invertible** are matrices that don't have an inverse.

# Properties of Matrices

Matrices have many properties in Linear Algebra.

<table>
<tr>
<td>Distributivity</td><td>$A(B+C)=AB+AC$</td>
</tr>
<tr>
<td>Non-commutativity</td><td>$AB \neq BA$</td>
</tr>
<tr>
<td>Associative property of multiplication</td><td>$(AB)C = A(BC)$</td>
</tr>
<tr>
<td>Multiplicative identity property</td><td>$IA = AI = A$</td>
</tr>
<tr>
<td></td><td>$A^{-1}A = AA^{-1} = I$
</td>
</tr>    
<tr>
<td></td><td>$(AB)^{-1} = B^{-1}A^{-1}$</td>
</tr>    
<tr>
<td>Reversivity of the transpose of a product of matrices,</td><td>$(AB)^T = B^TA^T$</td>
</tr>    
</table>

---