# NumPy Homework

# A

## 1) import numpy library with his usual alias!

In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

Matplotlib is building the font cache; this may take a moment.


## 2) Create a random matrix, which has 2 columns and 20 rows. With this we will then create a pandas DataFrame!

In [3]:
ratings_values = np.random.randint(10, size = (20,2))
ratings = pd.DataFrame(ratings_values, columns=['Price', 'Quality'])
print(ratings_values)
print()
display(ratings)

[[9 3]
 [6 9]
 [1 5]
 [6 1]
 [6 1]
 [2 4]
 [6 8]
 [4 2]
 [2 7]
 [6 5]
 [2 7]
 [6 5]
 [3 0]
 [1 5]
 [3 2]
 [6 6]
 [9 6]
 [6 3]
 [9 5]
 [9 2]]



Price  Quality
0       9        3
1       6        9
2       1        5
3       6        1
4       6        1
5       2        4
6       6        8
7       4        2
8       2        7
9       6        5
10      2        7
11      6        5
12      3        0
13      1        5
14      3        2
15      6        6
16      9        6
17      6        3
18      9        5
19      9        2

## 3) Create two vectors from the previous DataFrame. We will use the same values from the previous DataFrame which we already have been created. The first one contains the evaluations which show the customer satisfaction for the prices, and the second one contains for the quality. How big how good! We will then print the vectors.

##### Hint: pd.DataFrame['column_name'] gives us a Series from a DataFrame. We can use it with the same functions as DataFrames.

In [4]:
price =   pd.DataFrame({'Price':ratings_values[:,0]}) # < write your code here >
quality =  pd.DataFrame({'Price':ratings_values[:,1]})# < write your code here >


print('Price: ', price)
print('Quality: ', quality)

Price:      Price
0       9
1       6
2       1
3       6
4       6
5       2
6       6
7       4
8       2
9       6
10      2
11      6
12      3
13      1
14      3
15      6
16      9
17      6
18      9
19      9
Quality:      Price
0       3
1       9
2       5
3       1
4       1
5       4
6       8
7       2
8       7
9       5
10      7
11      5
12      0
13      5
14      2
15      6
16      6
17      3
18      5
19      2


## 4) Find the total numbers of visitors.

In [5]:
visitors_count =len(quality) # < write your code here >

print('Number of visitors:', visitors_count)

Number of visitors: 20


## 5) Find and print the average ratings for each column using numpy functions (we will find the mean and median values)

In [7]:
print('The mean of the price ratings: ', price.mean()) # < write your code here >
print('The median of the price ratings', price.median()) # < write your code here >

print('The mean of the quality ratings: ', quality.mean()) # < write your code here >
print('The median of the quality ratings', quality.median()) # < write your code here >

The mean of the price ratings:  Price    5.1
dtype: float64
The median of the price ratings Price    6.0
dtype: float64
The mean of the quality ratings:  Price    4.3
dtype: float64
The median of the quality ratings Price    5.0
dtype: float64


## 6) Create a new vector which is the average of the ratings of two columns, price and quality. We will name it as mean_ratings. It will show the average rating for each customer. Round elements of the array to the nearest integer.

In [8]:
mean_ratings = mean_ratings = np.round((price.values+quality.values).T*0.5)[0].astype(int)# < write your code here >
print(mean_ratings)

[6 8 3 4 4 3 7 3 4 6 4 6 2 3 2 6 8 4 7 6]


## 7) Create ratings_values matrix again with the all three vectors. Average ratings, which has just been calculated in the previous exercise, should be the third column of the new matrix. All values in the matrix should be integer! New matrix should have 20 rows and 3 columns!

In [9]:
new_ratings_values = np.array([ratings_values[:,0],ratings_values[:,1],mean_ratings]).T# < write your code here >
print(new_ratings_values)
print(type(new_ratings_values))
print(new_ratings_values.shape)

[[9 3 6]
 [6 9 8]
 [1 5 3]
 [6 1 4]
 [6 1 4]
 [2 4 3]
 [6 8 7]
 [4 2 3]
 [2 7 4]
 [6 5 6]
 [2 7 4]
 [6 5 6]
 [3 0 2]
 [1 5 3]
 [3 2 2]
 [6 6 6]
 [9 6 8]
 [6 3 4]
 [9 5 7]
 [9 2 6]]
<class 'numpy.ndarray'>
(20, 3)


In [10]:
new_ratings = pd.DataFrame(new_ratings_values, columns=['Price', 'Quality', 'Average'])
display(new_ratings)

Price  Quality  Average
0       9        3        6
1       6        9        8
2       1        5        3
3       6        1        4
4       6        1        4
5       2        4        3
6       6        8        7
7       4        2        3
8       2        7        4
9       6        5        6
10      2        7        4
11      6        5        6
12      3        0        2
13      1        5        3
14      3        2        2
15      6        6        6
16      9        6        8
17      6        3        4
18      9        5        7
19      9        2        6

# B

## 1) Create *Mean Absolute Error (MAE)* function

\begin{equation}
MAE=\frac{1}{n}\sum_{i=1}^n|target_i - predictions_i|
\end{equation}

In [11]:
def mae(target, predictions):
    return abs(target-predictions)/target.size# < write your code here >

## 2) Create two arrays each of them has $100$ observations. We will use them for *target* and *predictions* labelling. The target array should consist only $0$ or $1$ values which are random created, while predictions only integer $1$. The target array should have a *binomial distribution* which gives $1$ with $60$% probability.

In [41]:
target = np.random.binomial(1,0.6,100) # < write your code here >
predictions = np.ones(100, dtype=int) # < write your code here >

print(target)
print()
print(predictions)

[1 1 0 1 1 1 1 0 0 1 1 0 1 0 1 1 1 1 0 0 0 1 1 1 1 1 0 1 1 0 0 1 1 1 1 0 1
 1 0 0 0 1 0 1 0 1 1 0 0 0 1 1 1 1 1 1 1 1 0 0 1 1 0 0 0 1 0 1 1 0 1 1 0 0
 1 0 1 1 1 1 0 0 1 1 1 0 1 0 1 1 0 0 1 0 1 0 0 1 1 1]

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


## 3) Find the *MAE* with your mae function

In [42]:
mean_absolute_error =  mae(target,predictions) # < write your code here >

## 4)  Run the code in this step. Observe the printed outputs. Try to run the codes a few times from step 2. What do you think about the results? Give your thoughts shortly with 3 - 5 sentences about why two outputs are the same. What is your conclusion?

In [16]:
print(1-np.mean(target))

print(mean_absolute_error)

0.41000000000000003
[0.01 0.   0.   0.   0.   0.01 0.   0.01 0.   0.   0.   0.01 0.01 0.
 0.   0.   0.   0.01 0.   0.01 0.   0.   0.01 0.   0.01 0.01 0.01 0.
 0.01 0.   0.01 0.   0.   0.   0.   0.   0.01 0.01 0.   0.   0.   0.
 0.01 0.01 0.   0.01 0.01 0.01 0.01 0.   0.   0.   0.01 0.01 0.   0.
 0.   0.01 0.   0.   0.   0.   0.01 0.   0.01 0.   0.01 0.   0.   0.01
 0.   0.01 0.01 0.01 0.   0.   0.   0.01 0.01 0.   0.   0.01 0.01 0.01
 0.   0.01 0.01 0.   0.   0.01 0.   0.   0.01 0.   0.   0.01 0.   0.
 0.   0.  ]


 ### < write your conclusion here >

## 5) We have always chosen $1$ in our predictions, but the actual values at the target have changed each time. How likely is it that we got it right each time, and what determines this?

 ### < write your answer here >

# C

## 1) Create a Pythagorean function using *np.dot()* to calculate vector length

$$v = [x, y] ==> len_v = \sqrt{x^2+y^2}$$

In [18]:
def pythagorean_length(vector):
    return np.dot(vector,vector)**(1/2) # < write your code here >

## 2) Calculate the length of the given vector using your *pythagorean_length* function and check your result comparing with the given

In [19]:
a = np.array([3, 4])

print((pythagorean_length(a))) # < write your code here >

print(((a[0] ** 2) + (a[1] ** 2)) ** 0.5)

5.0
5.0


## 3) Find the shortest distance (Euclidean distance) using *np.dot()* between the given two vectors and compare the results to check

In [21]:
a = np.array([5, 6])
b = np.array([1, 3])

c = pythagorean_length(a-b) # < write your code here >
print('The distance between a and b is', c)

from scipy.spatial import distance
print('The distance between a and b should be', distance.euclidean(a, b))

The distance between a and b is 5.0
The distance between a and b should be 5.0


# D - Obfuscating Data

It is best to obfuscate data by multiplying the numerical features (they can be seen as the matrix $X$) by an invertible matrix $P$. 

$$
X' = X \times P
$$

Try to do that and check how the features' values will look like after the transformation. By the way, the invertible property is important here so make sure that $P$ is indeed invertible.

In [22]:
# pd.DataFrame
columns = ['gender', 'age', 'salary', 'family_members']
data = np.array([np.random.choice([0, 1], size=1000), 
                 np.random.randint(18, 100, 1000), 
                 np.random.normal(25000, 5000, 1000).astype(int), 
                 np.random.randint(0, 10, 1000)
                ])

personal_data = pd.DataFrame(data.T, columns=columns)
display(personal_data.tail(10))

gender  age  salary  family_members
990       1   84   17055               9
991       0   37   24764               6
992       1   64   20006               2
993       1   62   21356               0
994       0   38   20742               5
995       1   66   28177               2
996       1   67   25364               5
997       1   28   27674               6
998       1   42   16313               3
999       1   59   20075               8

In [37]:
X = personal_data.values # < write your code here >

In [40]:
P = np.random.randint(0,10,(1000,1000))# < write your code here >
# < write your code here >

**(Hint:** https://numpy.org/doc/stable/reference/random/generator.html **)**

In [34]:
x2= np.dot(P,X) # < write your code here >
print(x2)

[[     2289    255347 109545591     19865]
 [     2368    254694 111635388     19871]
 [     2413    266170 114144193     20552]
 ...
 [     2304    266861 115722967     20896]
 [     2423    269091 116679401     21363]
 [     2373    262039 113946747     20451]]


In [35]:

X =np.dot(np.linalg.inv(P),x2)

#### Can you guess the customers' ages or income after the transformation?

In [36]:
# Secure Data
pd.DataFrame(x2).describe # < write your code here >

<bound method NDFrame.describe of         0       1          2      3
0    2289  255347  109545591  19865
1    2368  254694  111635388  19871
2    2413  266170  114144193  20552
3    2561  272728  115679780  20787
4    2410  258550  112637552  20284
..    ...     ...        ...    ...
995  2418  266678  115980515  21174
996  2365  260292  113112702  20272
997  2304  266861  115722967  20896
998  2423  269091  116679401  21363
999  2373  262039  113946747  20451

[1000 rows x 4 columns]>

#### write your conlusion here
...

#### Can you recover the original data from $X'$ if you know $P$? Try to check that with calculations by moving $P$ from the right side of the formula above to the left one. The rules of matrix multiplication are really helpful here.

In [29]:
x_new=np.dot(np.linalg.inv(P),x2)# < write your code here >

In [30]:
print(X[1:3])
print(10*"-")
print(x2[1:3])
print(10*"-")
print(P[1:3])# Printing all three cases for a few customers

[[    1    90 31906     9]
 [    1    55 23880     8]]
----------
[[     2368    254694 111635388     19871]
 [     2413    266170 114144193     20552]]
----------
[[6 0 7 ... 5 2 5]
 [7 6 0 ... 2 6 9]]


In [31]:
# Original Data
personal_data.tail(10)

gender  age  salary  family_members
990       1   84   17055               9
991       0   37   24764               6
992       1   64   20006               2
993       1   62   21356               0
994       0   38   20742               5
995       1   66   28177               2
996       1   67   25364               5
997       1   28   27674               6
998       1   42   16313               3
999       1   59   20075               8

In [32]:
# Secure Data
pd.DataFrame(x2).tail(10)  # < write your code here >

0       1          2      3
990  2318  260691  112920486  20348
991  2445  271323  118556044  20923
992  2294  263209  114523483  20886
993  2265  255640  111558898  20178
994  2393  263833  114141237  20504
995  2418  266678  115980515  21174
996  2365  260292  113112702  20272
997  2304  266861  115722967  20896
998  2423  269091  116679401  21363
999  2373  262039  113946747  20451

In [33]:
# Recovered Data
pd.set_option('display.float_format', '{:.2f}'.format)
pd.DataFrame(x_new).astype('int').tail(10) # < write your code here >

0   1      2  3
990  1  84  17055  9
991  0  37  24764  6
992  0  63  20005  1
993  1  62  21356  0
994  0  37  20741  4
995  0  65  28176  1
996  0  66  25363  4
997  1  28  27674  6
998  1  42  16313  3
999  0  58  20074  7

#### write your conlusion here
...

---

# USEFUL INFORMATIONS

##### Matrices and Matrix Operations

- **A matrix** is a rectangular numeric table or two-dimensional array consisting of m rows and n columns.
- **A transpose of the matrix** is a matrix operation when its rows become columns with the same numbers.- **Dummy code** is a simple code that doesn't mean anything.
- **An identity matrix** is a square matrix with ones on the main diagonal and zeros elsewhere.
- **An inverse matrix** for a square matrix A is a matrix A with a superscript -1 whose product with A is equal to the identity matrix.
- **Invertible matrices** are matrices that have an inverse.
- **Non-invertible** are matrices that don't have an inverse.

# Properties of Matrices

Matrices have many properties in Linear Algebra. A few of them are listed here which can help with the analytical proof in this project.

<table>
<tr>
<td>Distributivity</td><td>$A(B+C)=AB+AC$</td>
</tr>
<tr>
<td>Non-commutativity</td><td>$AB \neq BA$</td>
</tr>
<tr>
<td>Associative property of multiplication</td><td>$(AB)C = A(BC)$</td>
</tr>
<tr>
<td>Multiplicative identity property</td><td>$IA = AI = A$</td>
</tr>
<tr>
<td></td><td>$A^{-1}A = AA^{-1} = I$
</td>
</tr>    
<tr>
<td></td><td>$(AB)^{-1} = B^{-1}A^{-1}$</td>
</tr>    
<tr>
<td>Reversivity of the transpose of a product of matrices,</td><td>$(AB)^T = B^TA^T$</td>
</tr>    
</table>

---