# NumPy Homework

# A

## 1) import numpy library with his usual alias!

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

## 2) Create a random matrix, which has 2 columns and 20 rows. With this we will then create a pandas DataFrame!

In [2]:
ratings_values = np.random.randint(low=1, high=11, size=(20, 2))
ratings = pd.DataFrame(ratings_values, columns=['Price', 'Quality'])
print(ratings_values)
print()
display(ratings)

[[ 2 10]
 [ 3 10]
 [ 5  1]
 [ 1  3]
 [ 2  9]
 [ 2  1]
 [ 1  9]
 [ 2  3]
 [ 3  1]
 [ 5  2]
 [10  5]
 [ 7  4]
 [ 7  1]
 [ 9  7]
 [ 3  9]
 [ 3  9]
 [ 8 10]
 [ 9 10]
 [ 3  7]
 [ 6 10]]



Price  Quality
0       2       10
1       3       10
2       5        1
3       1        3
4       2        9
5       2        1
6       1        9
7       2        3
8       3        1
9       5        2
10     10        5
11      7        4
12      7        1
13      9        7
14      3        9
15      3        9
16      8       10
17      9       10
18      3        7
19      6       10

## 3) Create two vectors from the previous DataFrame. We will use the same values from the previous DataFrame which we already have been created. The first one contains the evaluations which show the customer satisfaction for the prices, and the second one contains for the quality. How big how good! We will then print the vectors.

##### Hint: pd.DataFrame['column_name'] gives us a Series from a DataFrame. We can use it with the same functions as DataFrames.

In [3]:
price = ratings.loc[:, 'Price']
quality = ratings.loc[:, 'Quality']


print('Price: ', price)
print('Quality: ', quality)

Price:  0      2
1      3
2      5
3      1
4      2
5      2
6      1
7      2
8      3
9      5
10    10
11     7
12     7
13     9
14     3
15     3
16     8
17     9
18     3
19     6
Name: Price, dtype: int32
Quality:  0     10
1     10
2      1
3      3
4      9
5      1
6      9
7      3
8      1
9      2
10     5
11     4
12     1
13     7
14     9
15     9
16    10
17    10
18     7
19    10
Name: Quality, dtype: int32


## 4) Find the total numbers of visitors.

In [4]:
visitors_count = ratings.shape[0]

print('Number of visitors:', visitors_count)

Number of visitors: 20


## 5) Find and print the average ratings for each column using numpy functions (we will find the mean and median values)

In [6]:
print('The mean of the price ratings: ',ratings['Price'].mean())
print('The median of the price ratings',  ratings['Price'].median())

print('The mean of the quality ratings: ',  ratings['Quality'].mean())
print('The median of the quality ratings', ratings['Quality'].median())

The mean of the price ratings:  4.55
The median of the price ratings 3.0
The mean of the quality ratings:  6.05
The median of the quality ratings 7.0


## 6) Create a new vector which is the average of the ratings of two columns, price and quality. We will name it as mean_ratings. It will show the average rating for each customer. Round elements of the array to the nearest integer.

In [16]:
mean_ratings = (ratings['Price'] + ratings['Quality']) / 2
ratings['mean_ratings'] = mean_ratings.round().astype(int)
print(mean_ratings)

0     6.0
1     6.5
2     3.0
3     2.0
4     5.5
5     1.5
6     5.0
7     2.5
8     2.0
9     3.5
10    7.5
11    5.5
12    4.0
13    8.0
14    6.0
15    6.0
16    9.0
17    9.5
18    5.0
19    8.0
dtype: float64


## 7) Create ratings_values matrix again with the all three vectors. Average ratings, which has just been calculated in the previous exercise, should be the third column of the new matrix. All values in the matrix should be integer! New matrix should have 20 rows and 3 columns!

In [17]:
new_ratings_values = np.column_stack((ratings['Price'], ratings['Quality'], ratings['mean_ratings']))
new_ratings_values = new_ratings_values.astype(int)
print(new_ratings_values)
print(type(new_ratings_values))
print(new_ratings_values.shape)

[[ 2 10  6]
 [ 3 10  6]
 [ 5  1  3]
 [ 1  3  2]
 [ 2  9  6]
 [ 2  1  2]
 [ 1  9  5]
 [ 2  3  2]
 [ 3  1  2]
 [ 5  2  4]
 [10  5  8]
 [ 7  4  6]
 [ 7  1  4]
 [ 9  7  8]
 [ 3  9  6]
 [ 3  9  6]
 [ 8 10  9]
 [ 9 10 10]
 [ 3  7  5]
 [ 6 10  8]]
<class 'numpy.ndarray'>
(20, 3)


In [18]:
new_ratings = pd.DataFrame(new_ratings_values, columns=['Price', 'Quality', 'Average'])
display(new_ratings)

Price  Quality  Average
0       2       10        6
1       3       10        6
2       5        1        3
3       1        3        2
4       2        9        6
5       2        1        2
6       1        9        5
7       2        3        2
8       3        1        2
9       5        2        4
10     10        5        8
11      7        4        6
12      7        1        4
13      9        7        8
14      3        9        6
15      3        9        6
16      8       10        9
17      9       10       10
18      3        7        5
19      6       10        8

# B

## 1) Create *Mean Absolute Error (MAE)* function

\begin{equation}
MAE=\frac{1}{n}\sum_{i=1}^n|target_i - predictions_i|
\end{equation}

In [1]:
def mae(target, predictions):
    return  np.mean(np.abs(predictions - target))

## 2) Create two arrays each of them has $100$ observations. We will use them for *target* and *predictions* labelling. The target array should consist only $0$ or $1$ values which are random created, while predictions only integer $1$. The target array should have a *binomial distribution* which gives $1$ with $60$% probability.

In [4]:
target =  np.random.binomial(n=1, p=0.6, size=100)  #n:number of trials in the binomial distribution p:probability of success
predictions = np.ones(100, dtype=int)

print(target)
print()
print(predictions)

[1 1 1 1 1 0 1 0 1 0 1 0 0 0 1 1 1 0 0 1 0 0 1 0 1 0 1 0 1 1 1 1 1 1 1 1 0
 1 0 1 0 0 1 1 1 1 1 1 1 1 1 1 0 1 1 0 0 1 1 0 1 0 0 1 1 1 1 1 0 1 1 0 1 1
 1 0 1 1 1 0 1 1 0 0 1 1 1 1 1 1 0 0 0 0 0 0 1 1 0 1]

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


## 3) Find the *MAE* with your mae function

In [5]:
mean_absolute_error =  mae(target, predictions)

## 4)  Run the code in this step. Observe the printed outputs. Try to run the codes a few times from step 2. What do you think about the results? Give your thoughts shortly with 3 - 5 sentences about why two outputs are the same. What is your conclusion?

In [8]:
print(1-np.mean(target))

print(mean_absolute_error)

0.36
0.36


print(1-np.mean(target)) kodu ile hedef dizideki 1'lerin yüzdesini hesaplayarak ortalama hatayı tahmin ediyoruz. Eğer hedef dizideki 1'lerin yüzdesi 60 ise, bu yaklaşık olarak 
0.4 ortalama hataya karşılık geliyor.

print(mean_absolute_error) kodu ile mae() fonksiyonu tarafından hesaplanan MAE değerini yazdırıyoruz. 
Eğer target dizisindeki 1'lerin yüzdesi yaklaşık olarak %60 ise( yani ortalama hata yaklaşık olarak 0.4 ise) o zaman 1-np.mean(target) ifadesinin sonucu da yaklaşık olarak 0.4 olacaktır.

## 5) We have always chosen $1$ in our predictions, but the actual values at the target have changed each time. How likely is it that we got it right each time, and what determines this?

Tahminlerimizde hep 1'i seçtiğimiz için tahminlerimiz her zaman doğru değildir ve hedefteki gerçek değerler her seferinde değiştiği için doğru yapma ihtimalimiz değişir. Gerçek değerlerin dağılımı binom dağılımına göre belirlendiği için, 0 veya 1 değeri alabilirler. Burada p=0.6 olduğu için hedef değerlerin %60'ının 1 olması beklenir. 

 Her seferinde doğru tahmin yapma olasılığı o gözlem için gerçek değerin tahminimizle aynı olma olasılığıdır.Bu olasılık hedef değerinin tahmin değerine bölünmesiyle hesaplanabilir. Tahmin değeri her zaman 1 olduğundan, doğru tahmin yapma olasılığı, hedef değerinin 1 olduğu durumlarda 1, hedef değerinin 0 olduğu durumlarda 0'dır.

# C

## 1) Create a Pythagorean function using *np.dot()* to calculate vector length

$$v = [x, y] ==> len_v = \sqrt{x^2+y^2}$$

In [19]:
def pythagorean_length(vector):
    return  np.sqrt(np.dot(vector, vector))

## 2) Calculate the length of the given vector using your *pythagorean_length* function and check your result comparing with the given

In [22]:
a = np.array([3, 4])

print(pythagorean_length(a)) 

print("<................................>") 

print(((a[0] ** 2) + (a[1] ** 2)) ** 0.5)

5.0
<................................>
5.0


## 3) Find the shortest distance (Euclidean distance) using *np.dot()* between the given two vectors and compare the results to check

In [24]:
a = np.array([5, 6])
b = np.array([1, 3])

c = np.sqrt((b[0] - a[0])**2 + (b[1] - a[1])**2)
print('The distance between a and b is', c)

from scipy.spatial import distance
print('The distance between a and b should be', distance.euclidean(a, b))

The distance between a and b is 5.0
The distance between a and b should be 5.0


# D - Obfuscating Data

It is best to obfuscate data by multiplying the numerical features (they can be seen as the matrix $X$) by an invertible matrix $P$. 

$$
X' = X \times P
$$

Try to do that and check how the features' values will look like after the transformation. By the way, the invertible property is important here so make sure that $P$ is indeed invertible.

## 1) Protect customers' personal data. It is necessary to develop a data transformation algorithm that makes it difficult to recover personal information in case the data falls into the wrong hands. This is called data masking or data obfuscation. However, the data must be protected in such a way that the quality of the machine learning models does not suffer. You don't need to choose the best model, just prove that the algorithm works correctly.

In [3]:
# pd.DataFrame
columns = ['gender', 'age', 'salary', 'family_members']
data = np.array([np.random.choice([0, 1], size=1000), 
                 np.random.randint(18, 100, 1000), 
                 np.random.normal(25000, 5000, 1000).astype(int), 
                 np.random.randint(0, 10, 1000)
                ])

personal_data = pd.DataFrame(data.T, columns=columns)
display(personal_data.tail(10))

gender  age  salary  family_members
990       1   95   32589               5
991       0   20   28659               3
992       0   77   20579               9
993       0   89   34087               8
994       0   61   27118               7
995       0   66   29957               1
996       1   65   14948               2
997       0   35   29914               2
998       0   32   18632               3
999       1   97   23480               2

In [4]:
personal_data_np = personal_data.values

In [6]:
key_matrix = np.random.randint(0, 10, size=personal_data_np.shape)

masked_data = np.multiply(personal_data_np, key_matrix).reshape(personal_data.shape)

**(Hint:** https://numpy.org/doc/stable/reference/random/generator.html **)**

In [10]:
np.random.seed(123)

In [11]:
key_matrix = np.random.randint(0, 10, size=personal_data_np.shape)

## 2) Can you guess the customers' ages or income after the transformation?

In [9]:
# Secure Data
pd.DataFrame(np.random.randn(100, 4), columns=list('ABCD')).describe() # < write your code here >

A           B           C           D
count  100.000000  100.000000  100.000000  100.000000
mean    -0.137359    0.053622   -0.082379    0.053738
std      0.951260    0.918561    0.978261    0.938981
min     -2.611896   -2.087513   -2.165749   -2.153992
25%     -0.806069   -0.548429   -0.877538   -0.508790
50%     -0.285612    0.087107   -0.086414    0.069392
75%      0.489081    0.703086    0.571616    0.585560
max      2.243356    2.334780    2.405084    2.131664

bu verilerin müşterilerin yaşları veya gelirleri gibi gerçek dünya verileriyle bir ilgisi yok, bu nedenle gerçek verileri tahmin etmek mümkün değildir.

## 3) Can you recover the original data from $X'$ if you know $P$? Try to check that with calculations by moving $P$ from the right side of the formula above to the left one. The rules of matrix multiplication are helpful here.

In [ ]:
# < write your code here >

In [ ]:
# Printing all three cases for a few customers

In [12]:
# Original Data
personal_data.tail(10)

gender  age  salary  family_members
990       1   95   32589               5
991       0   20   28659               3
992       0   77   20579               9
993       0   89   34087               8
994       0   61   27118               7
995       0   66   29957               1
996       1   65   14948               2
997       0   35   29914               2
998       0   32   18632               3
999       1   97   23480               2

In [ ]:
# Secure Data
pd.DataFrame("<............>").tail(10)  # < write your code here >

In [ ]:
# Recovered Data
pd.set_option('display.float_format', '{:.2f}'.format)
pd.DataFrame(<............>).astype('int').tail(10) # < write your code here >

#### write your conlusion here
...

---

# USEFUL INFORMATIONS

##### Matrices and Matrix Operations

- **A matrix** is a rectangular numeric table or two-dimensional array consisting of m rows and n columns.
- **A transpose of the matrix** is a matrix operation when its rows become columns with the same numbers.- **Dummy code** is a simple code that doesn't mean anything.
- **An identity matrix** is a square matrix with ones on the main diagonal and zeros elsewhere.
- **An inverse matrix** for a square matrix A is a matrix A with a superscript -1 whose product with A is equal to the identity matrix.
- **Invertible matrices** are matrices that have an inverse.
- **Non-invertible** are matrices that don't have an inverse.

# Properties of Matrices

Matrices have many properties in Linear Algebra.

<table>
<tr>
<td>Distributivity</td><td>$A(B+C)=AB+AC$</td>
</tr>
<tr>
<td>Non-commutativity</td><td>$AB \neq BA$</td>
</tr>
<tr>
<td>Associative property of multiplication</td><td>$(AB)C = A(BC)$</td>
</tr>
<tr>
<td>Multiplicative identity property</td><td>$IA = AI = A$</td>
</tr>
<tr>
<td></td><td>$A^{-1}A = AA^{-1} = I$
</td>
</tr>    
<tr>
<td></td><td>$(AB)^{-1} = B^{-1}A^{-1}$</td>
</tr>    
<tr>
<td>Reversivity of the transpose of a product of matrices,</td><td>$(AB)^T = B^TA^T$</td>
</tr>    
</table>

---