# NumPy Homework

# A

## 1) import numpy library with his usual alias!

In [77]:
import numpy as np # < write your code here >
import pandas as pd
import matplotlib.pyplot as plt
from IPython.display import display

## 2) Create a random matrix, which has 2 columns and 20 rows. With this we will then create a pandas DataFrame!

In [78]:
ratings_values = np.random.randint(10,100, (20,2)) # < write your code here >
ratings = pd.DataFrame(ratings_values, columns=['Price', 'Quality'])
print(ratings_values)
print()
display(ratings)

[[86 78]
 [61 73]
 [11 39]
 [68 62]
 [64 84]
 [46 96]
 [10 54]
 [64 86]
 [30 16]
 [61 85]
 [33 45]
 [95 23]
 [88 32]
 [65 72]
 [54 80]
 [28 60]
 [43 23]
 [44 45]
 [23 31]
 [18 35]]



Price  Quality
0      86       78
1      61       73
2      11       39
3      68       62
4      64       84
5      46       96
6      10       54
7      64       86
8      30       16
9      61       85
10     33       45
11     95       23
12     88       32
13     65       72
14     54       80
15     28       60
16     43       23
17     44       45
18     23       31
19     18       35

## 3) Create two vectors from the previous DataFrame. We will use the same values from the previous DataFrame which we already have been created. The first one contains the evaluations which show the customer satisfaction for the prices, and the second one contains for the quality. How big how good! We will then print the vectors.

##### Hint: pd.DataFrame['column_name'] gives us a Series from a DataFrame. We can use it with the same functions as DataFrames.

In [79]:
price =  pd.DataFrame({'Price':ratings_values[:,0]}) # < write your code here >
quality = pd.DataFrame({'Quality':ratings_values[:,1]}) # < write your code here >


print('Price: ', price)
print('Quality: ', quality)

Price:      Price
0      86
1      61
2      11
3      68
4      64
5      46
6      10
7      64
8      30
9      61
10     33
11     95
12     88
13     65
14     54
15     28
16     43
17     44
18     23
19     18
Quality:      Quality
0        78
1        73
2        39
3        62
4        84
5        96
6        54
7        86
8        16
9        85
10       45
11       23
12       32
13       72
14       80
15       60
16       23
17       45
18       31
19       35


## 4) Find the total numbers of visitors.

In [80]:
visitors_count = len(quality) # < write your code here >

print('Number of visitors:', visitors_count)

Number of visitors: 20


## 5) Find and print the average ratings for each column using numpy functions (we will find the mean and median values)

In [81]:
print('The mean of the price ratings: ', price.mean()) # < write your code here >
print('The median of the price ratings', price.median()) # < write your code here >

print('The mean of the quality ratings: ', quality.mean()) # < write your code here >
print('The median of the quality ratings', quality.median()) # < write your code here >

The mean of the price ratings:  Price    49.6
dtype: float64
The median of the price ratings Price    50.0
dtype: float64
The mean of the quality ratings:  Quality    55.95
dtype: float64
The median of the quality ratings Quality    57.0
dtype: float64


## 6) Create a new vector which is the average of the ratings of two columns, price and quality. We will name it as mean_ratings. It will show the average rating for each customer. Round elements of the array to the nearest integer.

In [82]:
mean_ratings = pd.DataFrame({'Mean Rating': np.round((price['Price'] + quality['Quality']) / 2)}) # < write your code here >
print(mean_ratings)

    Mean Rating
0          82.0
1          67.0
2          25.0
3          65.0
4          74.0
5          71.0
6          32.0
7          75.0
8          23.0
9          73.0
10         39.0
11         59.0
12         60.0
13         68.0
14         67.0
15         44.0
16         33.0
17         44.0
18         27.0
19         26.0


## 7) Create ratings_values matrix again with the all three vectors. Average ratings, which has just been calculated in the previous exercise, should be the third column of the new matrix. All values in the matrix should be integer! New matrix should have 20 rows and 3 columns!

In [83]:
new_ratings_values = np.concatenate((ratings_values, mean_ratings), axis=1) # < write your code here >
print(new_ratings_values)
print(type(new_ratings_values))
print(new_ratings_values.shape)

[[86. 78. 82.]
 [61. 73. 67.]
 [11. 39. 25.]
 [68. 62. 65.]
 [64. 84. 74.]
 [46. 96. 71.]
 [10. 54. 32.]
 [64. 86. 75.]
 [30. 16. 23.]
 [61. 85. 73.]
 [33. 45. 39.]
 [95. 23. 59.]
 [88. 32. 60.]
 [65. 72. 68.]
 [54. 80. 67.]
 [28. 60. 44.]
 [43. 23. 33.]
 [44. 45. 44.]
 [23. 31. 27.]
 [18. 35. 26.]]
<class 'numpy.ndarray'>
(20, 3)


In [84]:
new_ratings = pd.DataFrame(new_ratings_values, columns=['Price', 'Quality', 'Average'])
display(new_ratings)

Price  Quality  Average
0    86.0     78.0     82.0
1    61.0     73.0     67.0
2    11.0     39.0     25.0
3    68.0     62.0     65.0
4    64.0     84.0     74.0
5    46.0     96.0     71.0
6    10.0     54.0     32.0
7    64.0     86.0     75.0
8    30.0     16.0     23.0
9    61.0     85.0     73.0
10   33.0     45.0     39.0
11   95.0     23.0     59.0
12   88.0     32.0     60.0
13   65.0     72.0     68.0
14   54.0     80.0     67.0
15   28.0     60.0     44.0
16   43.0     23.0     33.0
17   44.0     45.0     44.0
18   23.0     31.0     27.0
19   18.0     35.0     26.0

# B

## 1) Create *Mean Absolute Error (MAE)* function

\begin{equation}
MAE=\frac{1}{n}\sum_{i=1}^n|target_i - predictions_i|
\end{equation}

In [85]:
def mae(target, predictions):
    return np.abs(target - predictions).mean() # < write your code here >

## 2) Create two arrays each of them has $100$ observations. We will use them for *target* and *predictions* labelling. The target array should consist only $0$ or $1$ values which are random created, while predictions only integer $1$. The target array should have a *binomial distribution* which gives $1$ with $60$% probability.

In [86]:
target =  np.random.binomial(1, 0.6, 100) # < write your code here >
predictions = np.ones(100, dtype=int) # < write your code here >

print(target)
print()
print(predictions)

[0 0 1 0 0 0 1 1 0 1 0 0 0 0 0 1 1 0 0 1 1 1 1 0 0 1 1 1 0 1 1 1 0 1 0 0 1
 1 0 1 1 0 1 1 0 0 0 0 0 0 1 1 1 0 1 0 1 1 1 0 1 0 1 0 1 0 1 0 1 0 1 1 1 1
 0 1 1 1 1 0 0 1 1 0 1 0 0 1 0 1 1 0 1 0 0 0 0 0 1 1]

[1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1]


## 3) Find the *MAE* with your mae function

In [87]:
mean_absolute_error = mae(target,predictions)  # < write your code here >

## 4)  Run the code in this step. Observe the printed outputs. Try to run the codes a few times from step 2. What do you think about the results? Give your thoughts shortly with 3 - 5 sentences about why two outputs are the same. What is your conclusion?

In [88]:
print(1-np.mean(target))

print(mean_absolute_error)

0.48
0.48


 ### The result of the "mae" function represents the absolute value of the mean difference in the "target" vector with the actual target values. Since all the elements of the "predictions" vector are "1", the result of the "mae" function and the result of the expression "1-np.mean(target)" are close to each other. However, these results may differ if a different "predictions" vector is used. < write your conclusion here >

## 5) We have always chosen $1$ in our predictions, but the actual values at the target have changed each time. How likely is it that we got it right each time, and what determines this?

 ### < write your answer here >

# C

## 1) Create a Pythagorean function using *np.dot()* to calculate vector length

$$v = [x, y] ==> len_v = \sqrt{x^2+y^2}$$

In [89]:
def pythagorean_length(vector):
    return np.sqrt(np.dot(vector,vector)) # < write your code here >

## 2) Calculate the length of the given vector using your *pythagorean_length* function and check your result comparing with the given

In [90]:
a = np.array([3, 4])

print(pythagorean_length(a)) # < write your code here >

print(((a[0] ** 2) + (a[1] ** 2)) ** 0.5)

5.0
5.0


## 3) Find the shortest distance (Euclidean distance) using *np.dot()* between the given two vectors and compare the results to check

In [91]:
a = np.array([5, 6])
b = np.array([1, 3])

c = pythagorean_length(a - b) # < write your code here >
print('The distance between a and b is', c)

from scipy.spatial import distance
print('The distance between a and b should be', distance.euclidean(a, b))

The distance between a and b is 5.0
The distance between a and b should be 5.0


# D - Obfuscating Data

It is best to obfuscate data by multiplying the numerical features (they can be seen as the matrix $X$) by an invertible matrix $P$. 

$$
X' = X \times P
$$

Try to do that and check how the features' values will look like after the transformation. By the way, the invertible property is important here so make sure that $P$ is indeed invertible.

In [92]:
# pd.DataFrame
columns = ['gender', 'age', 'salary', 'family_members']
data = np.array([np.random.choice([0, 1], size=1000), 
                 np.random.randint(18, 100, 1000), 
                 np.random.normal(25000, 5000, 1000).astype(int), 
                 np.random.randint(0, 10, 1000)
                ])

personal_data = pd.DataFrame(data.T, columns=columns)
display(personal_data.tail(10))

gender  age  salary  family_members
990       1   56   23510               9
991       1   85   30453               6
992       0   76   21236               1
993       1   25   27154               7
994       0   36   23977               8
995       0   49   28825               6
996       0   39   31292               2
997       1   92   23185               1
998       0   86   28038               9
999       1   27   24611               9

In [93]:
X = personal_data.values # < write your code here >

In [94]:
X

array([[    1,    35, 22277,     4],
       [    0,    30, 24736,     1],
       [    0,    22, 24042,     2],
       ...,
       [    1,    92, 23185,     1],
       [    0,    86, 28038,     9],
       [    1,    27, 24611,     9]])

In [95]:
rng = np.random.default_rng(seed=42) # < write your code here >
P = np.random.randint(0,10,(1000,1000)) # < write your code here >

In [96]:
P

array([[6, 5, 8, ..., 3, 9, 2],
       [7, 1, 8, ..., 2, 9, 6],
       [2, 6, 8, ..., 5, 7, 6],
       ...,
       [9, 8, 2, ..., 8, 3, 7],
       [9, 9, 4, ..., 4, 4, 4],
       [9, 7, 4, ..., 9, 9, 5]])

**(Hint:** https://numpy.org/doc/stable/reference/random/generator.html **)**

In [101]:
new = P @ X # < write your code here >
new

# I couldn't answer this question

array([[     2270,    253222, 109426728,     20137],
       [     2245,    255963, 112286924,     20458],
       [     2319,    263157, 113993642,     20584],
       ...,
       [     2288,    256269, 111888712,     20217],
       [     2382,    254456, 110890300,     19861],
       [     2353,    261575, 114663874,     20652]])

In [104]:
#X =np.dot(np.linalg.inv(P),new)

#### Can you guess the customers' ages or income after the transformation?

In [105]:
"""# Secure Data
pd.DataFrame().describe() # < write your code here >"""

0              1             2             3
count  1000.00000    1000.000000  1.000000e+03   1000.000000
mean   2369.14800  258479.976000  1.127569e+08  20326.738000
std      67.31057    5718.222148  2.345151e+06    486.987158
min    2135.00000  240669.000000  1.036045e+08  18299.000000
25%    2324.00000  254603.500000  1.112017e+08  19992.000000
50%    2372.00000  258398.500000  1.127564e+08  20328.500000
75%    2414.00000  262297.750000  1.143222e+08  20660.500000
max    2594.00000  276983.000000  1.207125e+08  21774.000000

#### write your conlusion here
...

#### Can you recover the original data from $X'$ if you know $P$? Try to check that with calculations by moving $P$ from the right side of the formula above to the left one. The rules of matrix multiplication are really helpful here.

In [ ]:
# < write your code here >

In [ ]:
# Printing all three cases for a few customers

In [ ]:
# Original Data
personal_data.tail(10)

In [ ]:
# Secure Data
pd.DataFrame(<............>).tail(10)  # < write your code here >

In [ ]:
# Recovered Data
pd.set_option('display.float_format', '{:.2f}'.format)
pd.DataFrame(<............>).astype('int').tail(10) # < write your code here >

#### write your conlusion here
...

---

# USEFUL INFORMATIONS

##### Matrices and Matrix Operations

- **A matrix** is a rectangular numeric table or two-dimensional array consisting of m rows and n columns.
- **A transpose of the matrix** is a matrix operation when its rows become columns with the same numbers.- **Dummy code** is a simple code that doesn't mean anything.
- **An identity matrix** is a square matrix with ones on the main diagonal and zeros elsewhere.
- **An inverse matrix** for a square matrix A is a matrix A with a superscript -1 whose product with A is equal to the identity matrix.
- **Invertible matrices** are matrices that have an inverse.
- **Non-invertible** are matrices that don't have an inverse.

# Properties of Matrices

Matrices have many properties in Linear Algebra. A few of them are listed here which can help with the analytical proof in this project.

<table>
<tr>
<td>Distributivity</td><td>$A(B+C)=AB+AC$</td>
</tr>
<tr>
<td>Non-commutativity</td><td>$AB \neq BA$</td>
</tr>
<tr>
<td>Associative property of multiplication</td><td>$(AB)C = A(BC)$</td>
</tr>
<tr>
<td>Multiplicative identity property</td><td>$IA = AI = A$</td>
</tr>
<tr>
<td></td><td>$A^{-1}A = AA^{-1} = I$
</td>
</tr>    
<tr>
<td></td><td>$(AB)^{-1} = B^{-1}A^{-1}$</td>
</tr>    
<tr>
<td>Reversivity of the transpose of a product of matrices,</td><td>$(AB)^T = B^TA^T$</td>
</tr>    
</table>

---